defaults: &defaults
  adapter: mysql
  username: root
  password: root
  host: localhost

development:
  database: yaeo_development
  <<: *defaults
test:
  database: yaeo_test
  <<: *defaults
production:
  database: yaeo_production
  <<: *defaults
