defaults: &defaults
  adapter: mysql
  username: root
  password: root
  host: localhost

development:
  database: yaeo_development.db
  <<: *defaults
test:
  database: yaeo_test.db
  <<: *defaults
production:
  database: yaeo_production.db
  <<: *defaults
